<a href="https://colab.research.google.com/github/amilsiddik/percobaan/blob/main/Random_Forest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sklearn.ensemble as ens
rf = ens.RandomForestClassifier(n_estimators=100)

In [2]:
import pandas as pd
df1 = pd.read_csv("/content/drive/MyDrive/Belajar/decisiontree_ch6.csv")
df1

    ID   mesin  bangku penggerak    label
0    1  bensin       4     depan    sedan
1    2  bensin       2     depan    sedan
2    3  bensin       8  belakang  minibus
3    4  diesel       6     depan  minibus
4    5  bensin       5  belakang  minibus
5    6  diesel       8  belakang  minibus
6    7  diesel       8  belakang  minibus
7    8  bensin       4     depan    sedan
8    9  diesel       7  belakang  minibus
9   10  bensin       4     depan    sedan
10  11  bensin       2     depan    sedan
11  12  diesel       6  belakang  minibus
12  13  diesel       8     depan  minibus
13  14  bensin       4     depan    sedan
14  15  diesel       2     depan    sedan
15  16  bensin       4     depan    sedan
16  17  bensin       8  belakang  minibus
17  18  bensin       4     depan    sedan
18  19  diesel       8  belakang  minibus
19  20  diesel       8  belakang  minibus
20  21  bensin       4     depan    sedan
21  22  bensin       4     depan  minibus
22  23  diesel       8  belakang  minibus
23  24  bensin       4     depan    sedan
24  25  bensin       5  belakang  minibus
25  26  bensin       4     depan  minibus
26  27  diesel       8  belakang  minibus
27  28  bensin       4     depan    sedan
28  29  bensin       7  belakang  minibus
29  30  bensin       4     depan    sedan
30  31  bensin       4     depan    sedan
31  32  bensin       2     depan    sedan
32  33  bensin       8  belakang  minibus
33  34  diesel       6     depan  minibus
34  35  bensin       5  belakang  minibus
35  36  diesel       8  belakang  minibus
36  37  diesel       4  belakang  minibus
37  38  bensin       4     depan    sedan
38  39  diesel       5  belakang  minibus
39  40  bensin       4     depan    sedan

In [3]:
encoding ={"mesin":{"bensin":0,"diesel":1},
           "penggerak":{"depan":0,"belakang":1}}
df1.replace(encoding,inplace=True)

In [4]:
X=df1.drop(['ID','label'],axis=1)
y=df1['label']

In [5]:
import sklearn.model_selection as ms
X_train, X_test, y_train, y_test = ms.train_test_split(X,y, test_size=0.2)
y_test

7       sedan
4     minibus
28    minibus
36    minibus
18    minibus
23      sedan
26    minibus
6     minibus
Name: label, dtype: object

In [6]:
rf.fit(X_train, y_train)

RandomForestClassifier()

In [7]:
print(rf)

RandomForestClassifier()

In [8]:
y_prediksi = rf.predict(X_test)

In [9]:
import sklearn.metrics as met
akurasi = met.accuracy_score(y_test, y_prediksi)
print (akurasi)

1.0

In [10]:
score = rf.feature_importances_
print(score)

[0.1520667  0.50532758 0.34260572]